name: Java CI with Maven

on:
  push:
    branches: [ "master" ] # 画像に「リポジトリー master」とあるのでmasterにします

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests with Maven
      # ↓ ここが重要！フォルダ名を指定して実行場所を移動させます
      working-directory: ./JUnitTest
      run: mvn test